### PR TITLE
Use single module and macro for derived node attribute types

### PR DESCRIPTION
**Pull request by sgoll**
## Description

This adds the remaining subtypes of `NodeAttributes`, i.e.

- `ua::MethodAttributes`
- `ua::ObjectTypeAttributes`
- `ua::VariableTypeAttributes`
- `ua::ReferenceTypeAttributes`
- `ua::DataTypeAttributes`
- `ua::ViewAttributes`

### CODE REVIEW

**Review by uklotzde — APPROVED** [review]

**Comment by LeanderGlanda** [comment]
Deriving the types with a macro looks good.

But I don't want to loose the `server.add_node()` method which supports all attribute/node types. Could we use generics for that method and for the Node struct? 

But how would you implement a generic `server.add_node()` method which supports all node / attribute types without having an enum?
Maybe by using a generic type as parameter?

**Review by LeanderGlanda — CHANGES_REQUESTED** [review]
Deriving the types with a macro looks good.

But I don't want to loose the server.add_node() method which supports all attribute/node types. Could we use generics for that method and for the Node struct?
Then we wouldn't require an enum, would we?

**Comment by LeanderGlanda** [comment]
In #133 I added the changes which i described above. So maybe take a look at that to investigate whether my requested changes here are good.

**Review by uklotzde — APPROVED** [review]
So this PR became an addition to #126 instead of an alternative?

**Comment by LeanderGlanda** [comment]
I wouldn't necessarily say an addition, but a better way to handle all the different attribute types.
So it replaces code from #126.

**Pull request merged**
